'use client';
import {useState} from 'react';
const products=['a collaborative design tool','a privacy-first browser','an app that makes budgeting less painful','a coding tool for first-time builders','a calendar that protects your free time','a platform for independent creators','a smarter way to share research','a language-learning app','a tool that makes websites accessible','a community-owned music app','an app for finding local events','a better home for team knowledge','a low-waste delivery service','a tool that turns data into stories','a password manager','a platform for learning new skills'];
const audiences=['freelancers','skeptical early adopters','small business owners','people starting their first job','overwhelmed team leads','creatives who hate admin','remote teams','students on a budget','people switching careers','independent shop owners','busy parents','people who prefer doing things offline','first-time founders','community organisers','people learning something new','night owls'];
const formats=['a street poster series','a seven-day social experiment','a pop-up experience','a three-email story','a creator collaboration','a community challenge','a 30-second film','an interactive landing page','a tiny printed zine','a referral campaign','an unexpected product demo','a launch party','a podcast spot','a public installation','a useful free tool','a scavenger hunt'];
const twists=['without showing the product','using only five words per execution','with your audience as the heroes','without making a single feature claim','that gets strangers talking to each other','using a familiar everyday ritual','with a budget of $100','that people would save, not just like','with no paid media','built around a wonderfully specific frustration','that teaches something useful','that starts with a handwritten note','using humour instead of hype','that works without a screen','with an ending people can change','that makes the invisible visible'];
const pick=(items:string[])=>items[Math.floor(Math.random()*items.length)];
const initial='Launch a collaborative design tool for freelancers through a tiny printed zine—with no paid media.';
export default function CampaignPrompt(){
 const [prompt,setPrompt]=useState(initial);
 function next(){let fresh;do{fresh=`Launch ${pick(products)} for ${pick(audiences)} through ${pick(formats)}—${pick(twists)}.`;}while(fresh===prompt);setPrompt(fresh);}
 return <section className="campaign-lab" aria-labelledby="campaign-title"><div className="campaign-heading"><div><span className="eyebrow">a little creative stretch</span><h2 id="campaign-title">What would you make?</h2></div><img src="/brand/sparkle.svg" width="48" height="48" alt=""/></div><p className="campaign-brief" aria-live="polite" aria-atomic="true">{prompt}</p><button className="pill" onClick={next}>Give me a new brief <span aria-hidden="true">↗</span></button></section>
}
