'use client';
import {useEffect,useRef,useState} from 'react';
import ConnectionField from './ConnectionField';
const prompts=[{question:'does this make sense?',context:'a second pair of eyes before you hit publish.'},{question:'who’s tried this before?',context:'someone else has probably wrestled with it too.'},{question:'anyone up for a drink?',context:'close the tabs. keep the conversation going.'},{question:'what would you do?',context:'the kind of honest answer you can actually use.'}];
export default function ClubExperience(){
 const [paused,setPaused]=useState(false);const [prompt,setPrompt]=useState(0);const [burst,setBurst]=useState(0);const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const motion=matchMedia('(prefers-reduced-motion: reduce)');setPaused(motion.matches);const change=()=>setPaused(motion.matches);motion.addEventListener('change',change);const nodes=document.querySelectorAll<HTMLElement>('[data-reveal]');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}),{threshold:.12});nodes.forEach(n=>observer.observe(n));let raf=0;const update=()=>{raf=0;if(!root.current)return;const progress=Math.min(1,Math.max(0,window.scrollY/window.innerHeight));root.current.style.setProperty('--journey',String(motion.matches?0:progress));const total=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--read-progress',String(total>0?scrollY/total:0));};const scroll=()=>{if(!raf)raf=requestAnimationFrame(update);};window.addEventListener('scroll',scroll,{passive:true});update();return()=>{observer.disconnect();motion.removeEventListener('change',change);window.removeEventListener('scroll',scroll);cancelAnimationFrame(raf);};},[]);
 function connect(){setBurst(x=>x+1);setPrompt(x=>(x+1)%prompts.length);}
 return <div ref={root} className={`experience ${paused?'motion-paused':''}`}>
 <section className="universe" id="people" aria-labelledby="hero-title">
 <div className="hero-kicker">tech marketing club <span>est. 2026</span></div>
 <h1 id="hero-title">a small world.<br/><i>your kind of people.</i></h1>
 <p className="hero-description">a global community for marketers in tech.<br/>good questions. monthly meetups. actual friends.</p>
 <div className="universe-stage"><ConnectionField paused={paused} burst={burst}/><a className="orbit-photo orbit-object" href="#about"><img src="/kashvi.jpg" width="1536" height="1152" alt="Meet Kashvi, the founder"/><span>a note from kashvi</span></a><a className="orbit-logo orbit-object" href="#join"><img src="/club-logo.png" width="220" height="220" alt="tech marketing club — join us"/></a><a className="orbit-ticket orbit-object" href="#gatherings"><span>the next hello</span><strong>02<span> / oct</span></strong><span>11th st bar · 5–7 pm</span></a><button className="orbit-question orbit-object" onClick={connect} aria-label="Discover another conversation starter">{prompts[prompt].question}<span>tap to make a connection</span></button><span className="field-label" aria-hidden="true">different paths. same orbit.</span></div>
 <div className="hero-bottom"><a href="#conversation" className="scroll-cue"><span aria-hidden="true">↓</span> follow the thread</a><a className="pill" href="#join">find your people</a><button className="motion-toggle" onClick={()=>setPaused(x=>!x)} aria-pressed={paused}>{paused?'motion off':'motion on'} <span aria-hidden="true">{paused?'○':'◉'}</span></button></div>
 </section>
 <section className="conversation" id="conversation"><div className="section-index"><span>01 / the conversation</span><span>it starts with a question</span></div><div className="conversation-grid"><h2 data-reveal>you don't have to<br/><i>figure it out alone.</i></h2><div className="question-stage" data-reveal><div className="question-shadow" aria-hidden="true"/><div className="question-card"><span className="card-metadata">things worth asking / 0{prompt+1}</span><div aria-live="polite" aria-atomic="true"><p className="question-text" key={prompt}>{prompts[prompt].question}</p><p className="question-context">{prompts[prompt].context}</p></div><button onClick={connect} className="question-next">another question <span aria-hidden="true">↻</span></button></div></div></div><p className="conversation-foot">a group chat to turn to. a reason to meet in person.</p></section>
 </div>;
}
