import CampaignPrompt from './CampaignPrompt';
import Signup from './Signup';
import BuzzwordGame from './BuzzwordGame';
import ClubExperience from './ClubExperience';
export default function Home(){return <>
<a className="skip-link" href="#join">skip to joining the club</a>
<header className="site-header"><a href="#people" className="header-mark" aria-label="Tech Marketing Club home"><img src="/brand/tmc-icon.svg" width="150" height="50" alt="tmc"/></a><nav aria-label="Main navigation"><a href="#about">the story</a><a href="#gatherings">the next hello</a><a className="nav-join" href="#join">join the club</a></nav></header><div className="reading-line" aria-hidden="true"/>
<main><ClubExperience/><CampaignPrompt/>
<section className="founder-story" id="about"><div className="section-index"><span>02 / a familiar face</span><span>started by kashvi</span></div><div className="founder-grid"><figure className="founder-photo" data-reveal><img src="/kashvi.jpg" width="1536" height="1152" alt="Kashvi, founder of Tech Marketing Club"/></figure><div className="founder-copy" data-reveal><p>5+ years in marketing. I wanted a group chat of people doing this too.</p><p>Tech Marketing Club is for busy marketers who want to grow together.</p><a href="https://www.kashvi.xyz" target="_blank" rel="noreferrer" className="signature"><span>kashvi.xyz</span></a></div></div></section>
<section className="gathering" id="gatherings"><div className="section-index"><span>03 / off the internet</span><span>come for a drink. bring a marketer.</span></div><a className="event-ticket" href="https://www.instagram.com/techmarketingclub" target="_blank" rel="noreferrer" data-reveal><div className="ticket-date"><span>friday</span><strong>02</strong><span>october 2026</span></div><div className="ticket-main"><span>the next hello</span><h2>11th st bar.</h2><p>5–7 pm <span>·</span> details on instagram</p></div><div className="ticket-stub"><img src="/brand/tmc-icon.svg" width="150" height="50" alt="TMC"/><span>see you there</span></div></a></section>
<section className="join" id="join"><div className="section-index"><span>04 / your turn</span></div><div className="join-inner" data-reveal><img className="join-mark" src="/brand/tmc-icon-on-navy.svg" width="180" height="60" alt="Tech Marketing Club"/><h2>think bigger,<br/>think together.</h2><p>tech marketing news, in your inbox.</p><Signup/><div className="social-links"><a href="https://www.instagram.com/techmarketingclub" target="_blank" rel="noreferrer">instagram</a><span>·</span><a href="https://x.com/techmktclub" target="_blank" rel="noreferrer">twitter / x</a></div></div></section>
<BuzzwordGame/></main><footer><a className="footer-wordmark" href="#people"><img src="/brand/tmc-sub-logo.svg" width="170" height="73" alt="Tech Marketing Club"/></a><span>© {new Date().getFullYear()}</span></footer></>}
