import Signup from './Signup';
import BuzzwordGame from './BuzzwordGame';
export default function Home(){return <>
<header><a href="/" className="brand-logo" aria-label="Tech Marketing Club home"><img src="/club-logo.png" width="125" height="125" alt="tech marketing club"/></a><nav aria-label="Main navigation"><a href="#about">about</a><a href="#gatherings">meetups</a><a href="#join">join us</a></nav></header>
<main>
<section className="opening" aria-labelledby="intro-title"><div className="opening-note"><span className="index">a community for marketers in tech</span><h1 id="intro-title">a group chat.<br/>a familiar face.<br/><i>somewhere to turn.</i></h1><p>swap notes. ask questions. meet once a month.</p><a className="quiet-link" href="#join">join the club</a></div><figure className="portrait"><img src="/kashvi.jpg" width="1536" height="1152" alt="Kashvi, founder of Tech Marketing Club"/><figcaption><span>started by kashvi</span><span>01</span></figcaption></figure></section>
<section className="letter" id="about"><div className="margin-note">a note from kashvi</div><div className="letter-body"><h2>i've wanted this<br/><i>for a while.</i></h2><p>5+ years in marketing, a few sidequests, and one thing i kept missing: a group chat of people doing this too.</p><p>that's the idea behind tech marketing club. marketers in tech, monthly meetups around the world, and someone to ask “does this make sense?”</p><a className="signature" href="https://www.kashvi.xyz" target="_blank" rel="noreferrer">kashvi<span>kashvi.xyz</span></a></div></section>
<section className="gathering" id="gatherings"><div className="margin-note">see you in person</div><div className="event-content"><p className="index">up next</p><h2>see you at<br/><i>11th st bar.</i></h2><div className="event-details"><span>friday, october 2</span><span>5–7 pm</span><span>2026</span></div><p>come for a drink. bring a marketer.</p><a className="quiet-link" href="https://www.instagram.com/techmarketingclub" target="_blank" rel="noreferrer">details on instagram</a></div><div className="event-seal" aria-hidden="true"><img src="/club-icon.png" width="180" height="180" alt=""/></div></section>
<section className="join" id="join"><span className="index">meetup news, in your inbox.</span><h2>there's room<br/><i>for you here.</i></h2><Signup/><div className="social-links"><a href="https://www.instagram.com/techmarketingclub" target="_blank" rel="noreferrer">instagram</a><span>·</span><a href="https://x.com/techmktclub" target="_blank" rel="noreferrer">twitter / x</a></div></section>
<BuzzwordGame/></main><footer><a className="wordmark" href="/">tech marketing <i>club.</i></a><span>marketers in tech, together.</span><span>© {new Date().getFullYear()}</span></footer></>}
